version: "2"
services:
  web:
    build: .
    command: bash -c "rails server -e development -p 3500 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3500:3000"
      - "9393:9292"
    links:
     - solr:solr
     - redis
    depends_on:
      - solr
    env_file:
      - .env
    entrypoint:
      - /app/docker-entrypoint.sh
    network_mode: bridge

  solr:
    image: solr
    ports:
     - "8982:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - qwerteach
    network_mode: bridge
  redis:
    image: redis:latest
    ports:
      - "6379"
    network_mode: bridge
    
  proxy:
    image: nginx:alpine
    expose :
     - "80"
    volumes: 
     - ./proxy/qwdev.conf:/etc/nginx/conf.d/qwdev.conf
    links:
     - web
    environment: 
     - VIRTUAL_HOST=dev.qwerteach.com
     - LETSENCRYPT_HOST=dev.qwerteach.com
     - LETSENCRYPT_EMAIL=simon@hoggart.eu
     - VIRTUAL_PORT=80
    network_mode: bridge

volumes:
  data:

# copy solr config:
## docker cp solr/configsets/sunspot/conf/schema.xml qwerteach_solr_1:/opt/solr/server/solr/mycores/qwerteach/conf
## docker cp solr/configsets/sunspot/conf/solrconfig.xml qwerteach_solr_1:/opt/solr/server/solr/mycores/qwerteach/conf
# reload solr core:
## curl "http://localhost:8983/solr/admin/cores?action=RELOAD&core=qwerteach"
# re-index & start sunspot

