app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
redis:
  image: redis:3.2.4-alpine
  ports:
    # We'll bind our host's port 6379 to redis's port 6379, so we can use
    # Redis Desktop Manager (or other tools) with it:
    - 6379:6379
  volumes:
    # We'll mount the 'redis-data' volume into the location redis stores it's data:
    - redis-data:/var/lib/redis
  command: redis-server --appendonly yes