finish_meetings:
  every:
    - "5m"
  class: BigbluebuttonFinishMeetings
  description: "Checks for meetings that finished and mark as finished. Same as 'rake bigbluebutton_rails:meetings:finish'."

update_recordings:
  every:
    - "30m"
  class: BigbluebuttonUpdateRecordings
  description: "Gets the recordings in the server to populate the db. Same as 'rake bigbluebutton_rails:recordings:update'."

update_server_configs:
  every:
    - "1h"
  class: BigbluebuttonUpdateServerConfigs
  description: "Updates the server configs that are stored locally. Same as 'rake bigbluebutton_rails:server_configs:update'."

stat_message:
  every:
    - "1h"
  class: MessageStatWorker
  queue: message_stat
  description: "MaJ Stat UserMessage"

lesson_notifier:
  every:
    - "1m"
  class: LessonsNotifierWorker
  queue: bigbluebutton_rails
  description: "Notifies user is he's gt a lesson ready to begin"

expire_bookings:
  every:
    - "1m"
  class: ExpireBookings
  queue: bookings
  description: "refund bookings that expire"